sudo: required
services:
  - docker

before_install:
  - docker build -t suhailibnnisar/docker-multi-container -f ./client/Dockerfile.dev ./client

scripts:
  - docker run suhailibnnisar/docker-multi-container npm run test

after_success:
  - docker build -t suhailibnnisar/multi-client ./client
  - docker build -t suhailibnnisar/multi-nginx ./nginx
  - docker build -t suhailibnnisar/multi-server ./server
  - docker build -t suhailibnnisar/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push suhailibnnisar/multi-client
  - docker push suhailibnnisar/multi-nginx
  - docker push suhailibnnisar/multi-server
  - docker push suhailibnnisar/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: LearningDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-571149291614
  bucket_path: multi-docker
  access_key_id: $AWS_ACCESS
  secret_access_key: $AWS_SECRET
  on:
    branch: master
